### ISSUE TITLE
card description sync error for org properties

### ISSUE THREAD

**Issue by yangchenyun** [org-trello/org-trello#305]
for an org item with property:

```
* TODO: blahbalh
  :LOGBOOK:
  :LOCK: [2015-12-18 Fri 10:50]--[2015-12-18 Fri 14:25] =>  3:35
  :LOCK: [2015-12-17 Thu 15:21]--[2015-12-17 Thu 15:37] =>  0:16
  :LOCK: [2015-12-17 Thu 14:50]--[2015-12-17 Thu 15:15] =>  0:25
  :END:

  blah blah blah..
```

When it is synced to trello, the org properties is trimmed as:
```
  OGBOOK:
  OCK: [2015-12-18 Fri 10:50]--[2015-12-18 Fri 14:25] =>  3:35
  OCK: [2015-12-17 Thu 15:21]--[2015-12-17 Thu 15:37] =>  0:16
  OCK: [2015-12-17 Thu 14:50]--[2015-12-17 Thu 15:15] =>  0:25
  ND:
```
